language: java
sudo: false
script: mvn clean package
deploy:
  provider: releases
  api-key: ${GH_TOKEN}
  file_glob: true
  file: releng/com.thalesgroup.mde.openmbee.connector.mms.site/target/mms-capella-*.zip
  skip_cleanup: true
  on:
    tags: true
