version: 2
jobs:
  - build:
    working_directory: ~/mms-capella
    docker:
      - image: circleci/openjdk:8u252-jdk
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
          path: releng/com.thalesgroup.mde.openmbee.connector.mms.site/target/com.thalesgroup.mde.openmbee.connector.mms.site-1.0.0-SNAPSHOT.zip

  - publish-github-release:
    requires:
      - build
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=1.0.0-SNAPSHOT
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} releng/com.thalesgroup.mde.openmbee.connector.mms.site/target/com.thalesgroup.mde.openmbee.connector.mms.site-${VERSION}.zip
