version: 2
jobs:
  build:

    working_directory: ~/mms-capella

    docker:
      - image: circleci/openjdk:8u252-jdk

    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
          path: releng/com.thalesgroup.mde.openmbee.connector.mms.site/target/com.thalesgroup.mde.openmbee.connector.mms.site-*.zip
